import Head from 'next/head'
import { BsFillMoonStarsFill } from 'react-icons/bs'
import { AiFillTwitterCircle,AiFillLinkedin,AiFillYoutube } from 'react-icons/ai'
import Image from 'next/image'
import deved from '../public/dev-ed-wave.png'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=' bg-white px-10'>
        <section className='h-screen min-h-screen'>
          <nav className=' py-10 mb-12 flex justify-between'>
            <h1 className=' text-xl font-burtons'>Portfolio</h1>
            <ul className='flex items-center'>
              <li><BsFillMoonStarsFill className=' cursor-pointer text-xl' /></li>
              <li><a className=' bg-gradient-to-r  from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href='#'>Resume</a></li>
            </ul>
          </nav>
          <div className=' text-center p-10'>
            <h2 className=' text-5xl py-2 text-teal-600 font-medium'>Akash Yadav</h2>
            <h3 className=' text-2xl py-2 '>Developer and Designer</h3>
            <p className=' text-md py-5 leading-5 text-gray-800'>Freelancer Providing services for programming and design content needs.
              join me down below and let's get cracking!
            </p>
          </div>
          <div className=' text-5xl flex py-3 text-gray-600 justify-center gap-16'>
            <AiFillTwitterCircle/>
            <AiFillLinkedin/>
            <AiFillYoutube/>
          </div>
          <div className=' relative mx-auto bg-gradient-to-b from-teal-500 w-80 h-80 rounded-full mt-20 overflow-hidden'>
            <Image src={deved} layout="fill" objectFit="cover"/>
          </div>
        </section>
      </main>
    </div>
  )
}
